### ISSUE TITLE
Pulse sensor output question

### ISSUE THREAD

**Issue by sabdolla** [WorldFamousElectronics/PulseSensor_Amped_Arduino#4]
Hi,
I have a question about the output, the serial monitor read-out window continuously outputs things (e.g. s502, s503, etc.), even when my finger is not in the pulse.

Should I only pay attention to the top bar that ranges from 50 to 140? Are the units BMP?

Also, I am wondering if I can run the visualization code for mac or is it specific to windows?

Thank you,

Sara

**Comment by samuraipapa** [comment]
![screen800x500](https://cloud.githubusercontent.com/assets/3867041/8778666/2f62d8d0-2ecd-11e5-9164-f09c9be43068.jpeg)

Good Question.   

The Mac App is suppose to look like above screen grab. 
The **"Serial Monitor Read-Out" window** just runs a "live log" of everything Arduino is saying via Serial communication.   So, you can expect to see an rapid roll of numbers that are "Pre-fixed with a Letter".
this 

The Letter identifies what that number means. 
"S" Means Signal
"B" means BPM Number
"Q" is a Heart-rate Variability Number

For example:
"S511" or "S###" is the raw Signal number for the Pulse Sensor.  It's simply the intesty of light the optical sensor literally sees.   

1) Try Moving your finger on and off the sensor.  When you cover and uncover the sensor, you'll see that you can kind of control the Signal the "S" + "Some Number Between ~0-1000".  "S515" for example. 

**The Serial Monitor Read-Out" window** is simple a raw and live feed from Arduino to the Mac App.  The Visual Level Indicators, turn this live numbers feed into a "Digital Level".
<img width="1161" alt="screen shot 2015-07-20 at 11 04 17 am" src="https://cloud.githubusercontent.com/assets/3867041/8779031/250e2c8e-2ecf-11e5-9c09-c74d072a79f7.png">

**Comment by samuraipapa** [comment]
> *Should I only pay attention to the top bar that ranges from 50 to 140? Are the units BMP?

**Comment by sabdolla** [comment]
Yes, thank you so much. Can I also see the actual signal by running the visualization code?

**Comment by samuraipapa** [comment]
You mean by setting serial visualization = true?

On Monday, July 20, 2015, sabdolla <notifications@github.com> wrote:

> Yes, thank you so much. Can I also see the actual signal by running the
> visualization code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WorldFamousElectronics/PulseSensor_Amped_Arduino/issues/4#issuecomment-122950349>
> .
>


-- 
--------------------------------
Yury Gitman
Direct: (646) 263-5554
--------------------------------
--

**Comment by samuraipapa** [comment]
![asciiviz-1](https://cloud.githubusercontent.com/assets/3867041/8829505/ef6e7c2c-3064-11e5-8b9e-130ada2e5c54.png)
Yes, there is an ASCI Visualizer in the *Arduino Software* Itself.  
This will give you the below output on:  Mac, Windows, Linux

**Comment by sabdolla** [comment]
Thanks, I set it to false and it worked, very nice. What I had in mind is running the processing visualization app (http://pulsesensor.com/pages/processing-visualization). Can this app run on mac?
Thanks again,
Sara

**Comment by samuraipapa** [comment]
Yes.  The Processing App runs on Mac, Win, Linux.

**Comment by xueting123456** [comment]
Hi, hello. I saw your information on GitHub. Do you have the code to calculate the peak time difference through 2 pulse sensors?
