### ISSUE TITLE
Waveform Clipping at 1000

### ISSUE THREAD

**Issue by Nikeshbajaj** [WorldFamousElectronics/PulseSensor_Amped_Arduino#48]
Hello Dear
   I was stuck at clipped waveform as shown in attached figure, 
![issue](https://cloud.githubusercontent.com/assets/9660799/23611611/5bfb4230-0278-11e7-8087-35174216fa43.jpg)

Waveform is keep clipping at 1000. If I change power to 3.3v from 5v, waveform is not having clear QRS region

**Comment by biomurph** [comment]
Hello Dear,

The signal that Pulse Sensor provides is an analog signal, and the A-D converter in Arduino is 10bit. So it will read a signal from 0 (0V) to 1023 (5V) only. The signal is clipping because it is very large. You may want to try a different part of your body? Or different pressure of the sensor on your skin?

Also bear in mind that the Pulse Sensor is a PPG (https://en.wikipedia.org/wiki/Photoplethysmogram), and NOT an ECG. You will not see the QRS waveform with the Pulse Sensor.

**Comment by Nikeshbajaj** [comment]
Thank You, that explains a lot.
