### ISSUE TITLE
Advanced program not working as expected

### ISSUE THREAD

**Issue by Yerion** [WorldFamousElectronics/PulseSensor_Amped_Arduino#62]
Hello, 

I have been trying to get the advance code working, but i'm not getting the output i expect to see when i compare it to the examples. But the basic code does work more or less like expected. Any idea what could be wrong? I haven't changed the code and i'm using a arduino uno.

Results of the serial monitor, running the basic code and the advanced code.
![basic heartrate program](https://user-images.githubusercontent.com/24267554/30285558-c9586674-971e-11e7-8be0-f13427a62093.png)
![heartbeat advanced program](https://user-images.githubusercontent.com/24267554/30285559-c95a1cd0-971e-11e7-8852-b7c79f313c32.png)

I bought this sensor from a dutch webshop. So i'm not a 100% sure it is the original sensor. 
Here is a photo of the sensor:
![heartbeat sensor jpg](https://user-images.githubusercontent.com/24267554/30285872-e3355c90-971f-11e7-93c4-d5c72a37ec58.png)
![heartbeat sensor 2 jpg](https://user-images.githubusercontent.com/24267554/30285871-e332766a-971f-11e7-849c-4791ab992c21.png)

**Comment by biomurph** [comment]
Unfortunately, you have purchased a knockoff Pulse Sensor.
Sorry, but we can't help you troubleshoot it, since we have no idea of the parts or quality.
Please support the original makers and purchase from www.pulsesensor.com
You can also find our product at www.adafruit.com and www.sparkfun.com
It sounds like you are in the EU. There are many brick and mortar stores that receive stock from SparkFun, and may have Pulse Sensors. To find SparkFun distributors, go to the bottom of the SparkFun page and there you will find a link.

**Comment by Yerion** [comment]
Aah, that is a shame. I notified the seller and will buy a real one. Thanks for the quick reply.
