### ISSUE TITLE
Regarding Pulse sensor 

### ISSUE THREAD

**Issue by uanis301** [WorldFamousElectronics/PulseSensor_Amped_Arduino#91]
Hii
I am a student and I am doing project to get the heart sensor data using arduino but not able to get the accurate result. So, while I just started with coding and I am getting erratic values like 250+ and sometime only get around 20 or 30 BPM.

So please help me with this.

The Pulse sensor which I used is VMA340 from velleman. And for the coding I only used the example code from Pulse sensor playground Bpm to monitor code.

**Comment by biomurph** [comment]
@uanis301 
Thanks for reaching out!
This repository is no longer in use. Please use our PulseSensor Playground Library repository, and read the read-me, that's what it's there for!

As to your question. You purchased the [VMA340](https://www.velleman.eu/products/view/?id=450580) from Velleman. While we think that Velleman makes great kits and other cool stuff, this product is a knockoff our our original Pulse Sensor, and so I am unable to troubleshoot your problem since I have no idea what hardware they are using. 

I'll try to be as generous as possible, and recommend that you go to their forum and tell the that you're having trouble with their cloned part.

Please support the original makers of Open Source Hardware and purchase legit parts.
You can get Pulse Sensor from www.pulsesensor.com
We also sell through Adafruit and SparkFun.
Check out the SparkFun website. At the bottom of their pages they have a link to distributors that will show you where on the planet they ship their hardware to brick-and-mortar stores. There might be one in your area that sells our Pulse Sensor.
